# Generated by Django 3.0.3 on 2020-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ugdr',
            field=models.BinaryField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='uphone',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='upic',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='ustatus',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
