# Generated by Django 3.0.3 on 2020-02-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pmap', '0003_auto_20200212_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ugdr',
            field=models.IntegerField(default=1),
        ),
    ]
